// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAzYsJlgKwCyDsG5GGc1toYy5AI1RSVNWk',
    appId: '1:351582065449:web:a48559a936beeb61d29d38',
    messagingSenderId: '351582065449',
    projectId: 'test2-6e60a',
    authDomain: 'test2-6e60a.firebaseapp.com',
    storageBucket: 'test2-6e60a.firebasestorage.app',
    measurementId: 'G-T18DE6HLNZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCrlD8om9y9dNC_wUYj4WJiIRxLuY1Ehsw',
    appId: '1:351582065449:android:71a5a05850338ba2d29d38',
    messagingSenderId: '351582065449',
    projectId: 'test2-6e60a',
    storageBucket: 'test2-6e60a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBtJ-KOZhFpSQ5-iqXf1fRg7jbEN-sHiJw',
    appId: '1:351582065449:ios:bd5ef95c3d3a0301d29d38',
    messagingSenderId: '351582065449',
    projectId: 'test2-6e60a',
    storageBucket: 'test2-6e60a.firebasestorage.app',
    iosBundleId: 'com.example.test1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBtJ-KOZhFpSQ5-iqXf1fRg7jbEN-sHiJw',
    appId: '1:351582065449:ios:bd5ef95c3d3a0301d29d38',
    messagingSenderId: '351582065449',
    projectId: 'test2-6e60a',
    storageBucket: 'test2-6e60a.firebasestorage.app',
    iosBundleId: 'com.example.test1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAzYsJlgKwCyDsG5GGc1toYy5AI1RSVNWk',
    appId: '1:351582065449:web:828546e7b2231c2dd29d38',
    messagingSenderId: '351582065449',
    projectId: 'test2-6e60a',
    authDomain: 'test2-6e60a.firebaseapp.com',
    storageBucket: 'test2-6e60a.firebasestorage.app',
    measurementId: 'G-SRWKWJQYB2',
  );
}
